#+TITLE: Notes sur à propos de ce mémoire
#+DATE: Eté 2016


* TODO Quotes, reference and ideas to include in the final form

  - [ ] Bouchaud quotes on exogeneity, problem with Black Scholes and distributional
    assumptions (Bouchaud - La (regrettable) complexité des systèmes économiques.pdf)

  - [ ] Bouchaud again, saying they correlated news to the reaction of the financial
    market (5%)

  - [ ] Talk about computation time for various experiments.

  - [ ] *Intro* Rigollet, in his MIT course notes on stats learning, gives a nice overview
    of the history of high dimensional statistics and regression.

  - [ ] Discuss about the significance of the regularizers, particularly in the event
    where the analysis would restrict to an unbounded utility function. In other words,
    contrarily to eg. OLS, our method /needs/ a \ell_2 regularization in order to give a finite
    solution. 


* TODO References to find!

  - [ ] High dimensional exhogenous variable for finance (fallback to high dimensional
    nature of NLP if needed).


* TODO Theory to Improve

  - [ ] Introduce the concept of kernel in the theory and check how it scales with the rest

  - [ ] Check how we can leverage the other kind of bounds found within Chap. 10 of
    Mohri, eg. bound on expected risk using q'.


* TODO Theory and Experiments to include

  - [ ] NLP basic linear experiments

  - [ ] Use different kernels (polynomial + gaussian?) as part of parameters of the
    model.

  - [ ] Show how our problem is equivalent to a regression problem (or is it?)


* TODO Theory to ponder

  - [ ] Could we use the ``group sparsity'' in order to make a multi-asset general model?


